declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_ENABLE_LOCAL_AUTH_FALLBACK?: string;
    EXPO_PUBLIC_PREMIUM_GATES_ENABLED?: string;
    EXPO_PUBLIC_REVENUECAT_ANDROID_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_IOS_KEY?: string;
  }
}
